blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/hesprs/sync-engine/discussions
    about: Please ask and answer questions here instead of opening an issue.
