import { expect, test } from 'bun:test';
import { diffFindings, messageFindings } from '../../scripts/check-attribution';

test('a commit with a tool co-author is flagged, a human co-author is not', () => {
	const message = [
		'fix(#1): something',
		'',
		'Co-authored-by: Jane Doe <jane@example.com>',
		'Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>',
		'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
		'Co-authored-by: renovate[bot] <bot@renovateapp.com>',
	].join('\n');
	expect(messageFindings(message)).toStrictEqual([
		'Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>',
		'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
		'Co-authored-by: renovate[bot] <bot@renovateapp.com>',
	]);
});

test('watermarks and session links in a PR description are flagged', () => {
	expect(
		messageFindings(
			'Done.\n\n\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)',
		),
	).toHaveLength(1);
	expect(messageFindings('Claude-Session: https://claude.ai/code/session_x')).toHaveLength(1);
	expect(messageFindings('Made with Codex')).toHaveLength(1);
	expect(messageFindings('see https://chatgpt.com/codex/tasks/1')).toHaveLength(1);
});

test('ordinary words in a commit message are not flagged', () => {
	expect(
		messageFindings(
			'fix(#2): keep the cursor where it was\n\nCo-authored-by: Anna Smith <anna@example.com>',
		),
	).toStrictEqual([]);
	expect(
		messageFindings('docs: notes from AI assistants show up like any other note'),
	).toStrictEqual([]);
});

test('added lines are only checked for watermark shapes', () => {
	expect(
		diffFindings([
			'const cursor = editor.getCursor();',
			'Notes from other apps, AI assistants or scripts show up.',
			'// Generated with Claude Code',
			'\u{1F916} Generated by Copilot',
		]),
	).toStrictEqual(['// Generated with Claude Code', '\u{1F916} Generated by Copilot']);
});
