name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy-docs:
    runs-on: ubuntu-slim
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build docs
        run: bun build:docs

      - name: Deploy docs
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './docs/dist'
          clean-exclude: |
            modules/**
            modules.json
            modules-alternative.json
